### ISSUE TITLE
Nachrichten werden als gelesen markiert

### ISSUE THREAD

**Issue by tynsh** [FachschaftMathPhys/kummerkasten#15]
Kummer wird als gelesen markiert bevor die Dozenten den Kummer überhaupt sehen können.

How to reproduce:
- Kummer schreiben
- ins admin Panel -> Überprüfen -> Kummer auswählen
- dort steht "Zugehörige Dozierende: <name> gelesen", obwohl der Kummer noch nicht freigegeben ist.

**Comment by Sedrunum** [comment]
gefixt?
