### ISSUE TITLE
Hinweis auf weitere Angebote

### ISSUE THREAD

**Issue by flugdrachen** [FachschaftMathPhys/kummerkasten#23]
Ich denke, es wäre inhaltlich ganz sinnvoll, auf der Startseite des Kummerkastens auf die Psychosoziale Beratung für Studierende des Studierendenwerks und die Nightline hinzuweisen, da der Name Kummerkasten nach einer generellen Anlaufstelle für Probleme auch seelischer Art klingt.

**Comment by henrixapp** [comment]
Textvorschlag:
```
... Dir liegt etwas auf dem Herzen, was nicht an den Dozierenden bzw. seine Veranstaltung betrifft, dann können wir dir die Nightline Heidelberg oder die Psychosoziale Beratungsstelle für Studierende des Studierendenwerkes empfehlen. Ihre Kontaktdaten findest du hier(Link).
```
