### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhys/kummerkasten#36]
Veranstaltungen mit einem Sonderzeichen im Namen werden im Textfeld nicht korrekt angezeigt.
![image](https://user-images.githubusercontent.com/26827864/85200327-be24c080-b2f6-11ea-86a6-d75e0f6f0760.png)

**Comment by henrixapp** [comment]
Auf welchem System? Kann dies leider nicht bestätigen, bei mir werden sie korrekt angezeigt.

**Comment by christian-heusel** [comment]
Ich kann das aktuell auch nicht mehr reproduzieren ._.
